# -*- coding: utf-8 -*-
"""PR4.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qULBSbwFbglKx0BD08j4WNmCOCQxf_FG

Леонтьева Виктория БСВ23-01
02.05.2024

##1.1 Задание
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

file_csv = pd.read_csv("https://raw.githubusercontent.com/EvgeniiSopovGitHub/datasets_uni/main/okaivd/lab_4_raw_data.csv",sep=";")
file_csv.head()

file_csv.info()

#мои попытки
#file_csv.columns = ['date','unit_01','unit_02','unit_03','unit_04','unit_05','unit_06','unit_07','unit_08','unit_09','unit_10']
#file_csv.head()

#file_csv.fillna(288282)
file_csv.head()

file_csv.describe()

#мои попытки
#file_csv = file_csv[file_csv['date','unit_01','unit_02','unit_03','unit_04','unit_05','unit_06','unit_07','unit_08','unit_09','unit_10''unit_01'].notna()]
#file_csv.mean(axis=1)
#file_csv.fillna('mean')
file_csv.head()

#file_csv['mean']=file_csv.iloc[:,0:366].mean(axis=1)

n = ['unit_01','unit_02','unit_03','unit_04','unit_05','unit_06','unit_07','unit_08','unit_09','unit_10']
for i in n:
  file_csv[i].fillna(file_csv[i].mean(),inplace=True)
file_csv.head()

file_csv.info()

"""##1.3 Работа с данными"""

file_csv.iloc[1:,1:] = file_csv.iloc[1:, 1:].apply(pd.to_numeric)
file_csv.head()

file_csv['min'] =file_csv.iloc[:,1:].min(axis=1)
file_csv['max'] =file_csv.iloc[:,1:].max(axis=1)
file_csv['median'] =file_csv.iloc[:,1:].median(axis=1)

file_csv.head()

means = file_csv.iloc[:, 1:].mean(axis=1).round(2)
stds = file_csv.iloc[:, 1:].std(axis=1).round(2)
mean_std_strings = ["{}/{}".format(mean, std) for mean, std in zip(means, stds)]
file_csv.head(366)

#mean_std_strings = ["{}/{}".format(mean, std) for mean, std in zip(means, stds)]
file_csv['mean/std'] = mean_std_strings
file_csv.head(365)

average_annual_values = file_csv.iloc[1:, 1:-1].mean()
file_csv.loc["average annual", file_csv.columns[1]:file_csv.columns[-2]] = average_annual_values
file_csv.head(1000)

file_csv.head(365)